version: "2"
services:
  auth:
    restart: always
    image: "node:8-alpine"
    user: "node"
    working_dir: /home/harrison/repos/assistant/auth
    container_name: auth
    environment:
      - NODE_ENV=production
      - PORT=3421
    volumes:
      - ./:/home/harrison/repos/assistant/auth
    ports:
      - "3421:3421"
    command: "node simple"
networks:
  default:
    external:
      name: infrastructure_default
